In [1]:
import numpy as np

#### Accumulation phase compound interest formula $P_N(N) = P_0(N)j(\sum_{k=0}^{N-1}j^k)$
- $P_N$ = portfolio after $N$ years/cycles
- $P_0$ = investment per cycle
- $i$, $j$ = net interest return per cycle, $j = i+1$

In [2]:
# Basic P_N formula: constant P0 w/o withdrawals
def PN(P0,i,N):
    j=i+1
    e1 = [j**k for k in range(N+1)]
    e2 = [sum(e1[:n+1]) for n in range(N)]
    A = P0*j*np.array(e2)
    return A

#### Non-inflation-adjusted $P_0$ recurring investment:
- $P_0(N) = P_0(0)(1+IR)^N$ 
- $P_0(N)$ = inflation adjusted annual investment $P_0$ at $Nth$ cycle
- $P_0(0)$ = first investment payment
- $IR$ = inflation rate/cycle; $IR = \exp^{\frac{\log(1.58)}{22}}-1$ ; $P(22) = 1.58P(0)$ for 1998-2020 CPI; equivalently $IR = \frac{CPI(N)-CPI(0)}{CPI(0)}$ for a reference period $[0,N]$
- Adjusting for inflation: all future investments valued in terms of $N=0$ USD

In [38]:
# Calculating inflation on constant P0 recurring investment over N years (i.e. not adjusting 
# P0 for inflation if I can't afford to)
def P0_infl(P0,IR,N):
    return P0*np.array([(1+IR)**yr for yr in range(N+1)])

In [5]:
# Calculate P_N w/ or w/o inflation adjustment (i.e. IR = 0 means P_N is inflation adjusted so investing such as to
# keep investing at rate of f.ex. $30K in terms of 2020 dollars. IR > 0 means investing with non-adjusted amounts.
# P0_adj variable = required amounts P_0(t) such as to invest at P_0 rate in terms of 2020 dollars. 
P0_0 = 30e3
IR = 0.021009698851008674
N = 20
i = .05
inflation = np.array([(1+IR)**yr for yr in range(N)])

params_infl = (P0_0,IR,N)
#P0 = P0_infl(*params_infl)
params_PN = (P0_0,i,N)
# Divisor adjusts for value of PN relative to 2020 value
PN(*params_PN)

array([  31500.        ,   65931.7013033 ,  103520.2671792 ,
        144507.37832942,  189152.42927485,  237733.81108301,
        290550.28666075,  347922.46528528,  410194.38352736,
        477735.20023625,  550941.01380866,  630236.81055655,
        716078.55362375,  808955.42258264,  909392.21457205,
       1017951.91862029, 1135238.47563654, 1261899.73745316,
       1398630.63926609, 1546176.60085445])

In [6]:
params_PN = (P0,i,N)
# Divisor adjusts for value of PN relative to 2020 value
PN(*params_PN)

array([  31500.        ,   64575.        ,   99303.75      ,
        135768.9375    ,  174057.384375  ,  214260.25359375,
        256473.26627344,  300796.92958711,  347336.77606646,
        396203.61486979,  447513.79561328,  501389.48539394,
        557958.95966364,  617356.90764682,  679724.75302916,
        745210.99068062,  813971.54021465,  886170.11722538,
        961978.62308665, 1041577.55424099])

#### Case of portfolio $P_N(0)$ at $N=0$ w/o subsequent investments or withdrawals
- $P_N(N) = P_N(0)j^N$

#### Case of portfolio $P_N(0)$ at $N=0$ w/ periodic withdrawal p
- $P_N(N) = P_N(0)j^N - \frac{pj(j^N-1)}{i}$

In [36]:
def PN_N(P0,i,N):
    j=i+1
    return np.dot(P0,np.array([j**n for n in range(N+1)])) 

def PN_Np(PN_0,i,p,N):
    j=1+i
    return np.array([PN_0*j**n-(p*j*(j**n-1))/i for n in range(N+1)])

In [9]:
PN_0 = 1
N = 22
inflation = np.array([(1+IR)**yr for yr in range(N+1)])
#i = np.exp((np.log(1.2e6/150e3))/N)-1
i = -IR
PN_N(PN_0,i,N)

array([1.        , 0.9789903 , 0.95842201, 0.93828585, 0.91857275,
       0.89927381, 0.88038034, 0.86188381, 0.84377589, 0.82604842,
       0.80869339, 0.79170298, 0.77506954, 0.75878557, 0.74284371,
       0.72723679, 0.71195776, 0.69699974, 0.68235599, 0.66801989,
       0.653985  , 0.64024497, 0.62679362])

In [33]:
P0_infl(30e3,.034,20)

array([30000.        , 31020.        , 32074.68      , 33165.21912   ,
       34292.83657008, 35458.79301346, 36664.39197592, 37910.9813031 ,
       39199.95466741, 40532.7531261 , 41910.86673239, 43335.83620129,
       44809.25463213, 46332.76928962, 47908.08344547, 49536.95828262,
       51221.21486423, 52962.73616961, 54763.46919938, 56625.42715216])

In [39]:
PN_N(P0_infl(30e3,.034,20),0.063,20)

1900296.9522575643

In [30]:
# I inflation multiplier [1900,2016]
3.73282667e4/_

966.4801497155171

In [ ]:
PN_N(1,.09,)

In [ ]:
# x = 1.2e6+B
y = np.exp(np.log(x)-30*np.log(j))
y

In [ ]:
np.exp(np.log(_)/(30*np.log(j)))

In [ ]:
769.84*(1.0717)**30